name: intake-examples
channels:
  - conda-forge
dependencies:
  - nomkl
  - jupyter
  - tqdm
  - s3fs
  - intake
  - pre-commit
  ## intake plugins
  - intake-parquet
  - intake-xarray
  ## intake data packages
  - intake::anaconda-package-data
  - intake::us_crime
  ## pyviz dependencies
  - nodejs
  - scipy
  - bokeh<3.0
  - hvplot>=0.8.1
  - pyviz::holoviews
  - panel>=0.9.5
  - datashader
  - jupyterlab>=3.0
